export const CharacterClassList = {
  Wizard: {
    name: "Wizard",
    description: `Scholar of arcane magic, wielding spells through mastery of ancient knowledge, and capable of shaping reality to their will.`,
    health: 177,
    damage: 20,
    emoji: " 🧙‍♂️",
  },
  Sorcerer: {
    name: "Sorcerer",
    description: `Born with innate magical powers, able to cast spells through sheer force of will, and manipulating the fabric of reality.`,
    health: 155,
    damage: 19,
    emoji: " 🧙‍♀️",
  },
  Warlock: {
    name: "Warlock",
    description: `Pact-bound wielder of eldritch power, making deals with otherworldly beings to gain abilities, spells, and other advantages.`,
    health: 155,
    damage: 18,
    emoji: " 💀",
  },
  Rogue: {
    name: "Rogue",
    description: `Stealthy and cunning, skilled in theft, assassination, and trickery, and able to disable traps and locks.`,
    health: 155,
    damage: 17,
    emoji: " 👥",
  },
  Bard: {
    name: "Bard",
    description: `Skilled performer who uses music and magic to charm, inspire, and deceive others in equal measure.`,
    health: 160,
    damage: 16,
    emoji: " 🎵",
  },
  Ranger: {
    name: "Ranger",
    description: `Hunter and tracker, who moves through wilderness with ease, strikes from range with deadly accuracy, and forms bonds with animals.`,
    health: 205,
    damage: 15,
    emoji: " 🎯",
  },
  Fighter: {
    name: "Fighter",
    description: `Master of combat, skilled in a variety of weapons and techniques, and able to endure great physical punishment.`,
    health: 240,
    damage: 14,
    emoji: " 🗡️",
  },
  Monk: {
    name: "Monk",
    description: `Disciplined warrior, who channels their inner energy to strike with deadly precision and move with incredible speed.`,
    health: 164,
    damage: 13,
    emoji: " 🤜",
  },
  Barbarian: {
    name: "Barbarian",
    description: `Fierce warrior who embraces primal nature, using brute strength and raw power to crush enemies.`,
    health: 300,
    damage: 12,
    emoji: " 😠",
  },
  Paladin: {
    name: "Paladin",
    description: `Holy knight, who draws power from their faith and a sacred oath to smite evil, heal allies, and defend the innocent.`,
    health: 215,
    damage: 11,
    emoji: " 🛡️",
  },
  Cleric: {
    name: "Cleric",
    description: `Devout servant of a deity, wielding divine magic to heal allies, banish foes, and uphold their faith.`,
    health: 195,
    damage: 10,
    emoji: " ✝️",
  },
  Druid: {
    name: "Druid",
    description: `Protector of nature, shapeshifter, and wielder of primal magic that harnesses the power of the natural world.`,
    health: 190,
    damage: 10,
    emoji: " 🌿",
  },
};

//Wizard,Sorcerer,Warlock,Rogue,Bard,Ranger ,Fighter ,Monk, Barbarian,Paladin,Cleric,Druid
